export enum ActionTypes {
  TOGGLEFLAG = 'TOGGLEFLAG',
  MINECLICK = 'MINECLICK',
  NEWGAME = 'NEWGAME',
  LEVELCHANGE = 'LEVELCHANGE',
  EMPTYCELLCLICKED = 'EMPTYCELLCLICKED',
  CELLWITHVALUECLICKED = 'CELLWITHVALUECLICKED',
  GAMEPAUSED = 'GAMEPAUSED',
  GAMERESTORED = 'GAMERESTORED',
  RESTARTGAME = 'RESTARTGAME',
  SECSICREMENT = 'SECSICREMENT',
  TIMERSTART = 'TIMERSTART',
}

export enum LevelOptions {
  Easy,
  Intermediate,
  Expert,
}

export enum GameStatus {
  Active,
  Win,
  Fail,
  Paused,
  WinWithRecord
}
